# Generated by Django 4.1 on 2022-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
