# Generated by Django 4.1 on 2022-09-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
    ]
